---
- name: Configure llm-homelab base system
  ansible.builtin.import_playbook: 00-bootstrap.yml

- name: Apply base system configuration
  ansible.builtin.import_playbook: 01-system.yml

- name: Install NVIDIA driver
  ansible.builtin.import_playbook: 02-nvidia.yml
